<?php

namespace Lumis\StaffManagement\Database\Seeders;

use Illuminate\Database\Seeder;
use Lumis\StaffManagement\Entities\Position;

class PositionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $positions = [
            ['name' => 'Vice Chancellor'],
            ['name' => 'Deputy Vice Chancellor'],
            ['name' => 'University Registrar'],
            ['name' => 'Deputy University Registrar'],
            ['name' => 'University Librarian'],
            ['name' => 'Director of Finance'],
            ['name' => 'Deputy Director of Finance'],
            ['name' => 'Director of Research and Outreach'],
            ['name' => 'Director of Students Affairs'],
            ['name' => 'Director of Quality Assurance'],
            ['name' => 'Director of CARD'],
            ['name' => 'Director of ODL'],
            ['name' => 'Monitoring and Evaluation Specialist'],
            ['name' => 'Legal Advisor'],
            ['name' => 'ICT Manager'],
            ['name' => 'Procurement Manager'],
            ['name' => 'University Auditor'],
            ['name' => 'Farm Manager'],
            ['name' => 'Assistant Director of Finance (Management Accountant)'],
            ['name' => 'Assistant Director of Finance (Financial Accounting)'],
            ['name' => 'Head of Finance'],
            ['name' => 'Senior Accountant'],
            ['name' => 'Grants Accountant'],
            ['name' => 'Accountant'],
            ['name' => 'Accountant (Budget Variance Analysis)'],
            ['name' => 'Accountant (Projects)'],
            ['name' => 'Accountant (Asset Management)'],
            ['name' => 'Accountant (Management Reconciliation)'],
            ['name' => 'Accountant (Data Posting)'],
            ['name' => 'Accountant (Pay Roll)'],
            ['name' => 'Accountant (Debt & Credit Management)'],
            ['name' => 'Assistant Accountant'],
            ['name' => 'Senior Accounts Assistant (Data Posting)'],
            ['name' => 'Senior Accounts Assistant (Pay Roll)'],
            ['name' => 'Senior Accounts Assistant (Debt & Credit Management)'],
            ['name' => 'Accounts Assistant'],
            ['name' => 'Accounts Assistant (Data Posting)'],
            ['name' => 'Accounts Assistant (Pay Roll)'],
            ['name' => 'Accounts Assistant (Debt & Credit Management)'],
            ['name' => 'Accounts Cashier (Data Posting)'],
            ['name' => 'Cashier'],
            ['name' => 'Stores Officer'],
            ['name' => 'Stores Keeper'],
            ['name' => 'Administrative Officer'],
            ['name' => 'Marketing Officer'],
            ['name' => 'Media Specialist'],
            ['name' => 'Public Relations Officer'],
            ['name' => 'Assistant Internal Auditor'],
            ['name' => 'Assistant Risk Officer'],
            ['name' => 'Internal Audit Assistant '],
            ['name' => 'Procurement Officer'],
            ['name' => 'Assistant Procurement Officer '],
            ['name' => 'Procurement Assistant'],
            ['name' => 'Systems Engineer'],
            ['name' => 'Systems Administrator'],
            ['name' => 'Network Engineer'],
            ['name' => 'Database Administrator'],
            ['name' => 'User Support and Training Officer'],
            ['name' => 'Learning Management Systems Administrator'],
            ['name' => 'ICT Technician'],
            ['name' => 'Audio Visual Technician'],
            ['name' => 'Network Technician'],
            ['name' => 'Senior Research Fellow'],
            ['name' => 'Programmes Coordinator '],
            ['name' => 'Training and Consultancy Coordinator '],
            ['name' => 'Chief Executive Officer '],
            ['name' => 'Research Fellow'],
            ['name' => 'Research Professor'],
            ['name' => 'Associate Research Professor '],
            ['name' => 'Research Coordinator'],
            ['name' => 'Project Coordinator '],
            ['name' => 'Project Officer'],
            ['name' => 'Training Consultant'],
            ['name' => 'College Director'],
            ['name' => 'Deputy College Director'],
            ['name' => 'College Registrar'],
            ['name' => 'College Librarian'],
            ['name' => 'Quality Assurance Officer'],
            ['name' => 'Senior Assistant Registrar'],
            ['name' => 'Assistant Registrar - Administration'],
            ['name' => 'Assistant Registrar - Academics'],
            ['name' => 'Assistant Registrar - Human Resource'],
            ['name' => 'Assistant Registrar - Students Welfare'],
            ['name' => 'Executive Officer - Human Resource'],
            ['name' => 'Executive Officer - Academics'],
            ['name' => 'Executive Officer - Administration'],
            ['name' => 'Executive Officer - Transport'],
            ['name' => 'Maintenance Officer'],
            ['name' => 'Business Officer'],
            ['name' => 'Dean of Faculty'],
            ['name' => 'Deputy Dean of Faculty'],
            ['name' => 'Head of Department'],
            ['name' => 'Deputy Head of Department'],
            ['name' => 'Professor'],
            ['name' => 'Associate Professor'],
            ['name' => 'Senior Lecturer'],
            ['name' => 'Lecturer'],
            ['name' => 'Assistant Lecturer'],
            ['name' => 'Associate Lecturer'],
            ['name' => 'Senior Teaching Assistant'],
            ['name' => 'Teaching Assistant'],
            ['name' => 'Staff Associate'],
            ['name' => 'Classroom Attendant'],
            ['name' => 'Assistant Librarian (Technical Service)'],
            ['name' => 'Assistant Librarian (Reader Services)'],
            ['name' => 'Chief Library Assistant (Technical Service)'],
            ['name' => 'Chief Library Assistant (Reader Services)'],
            ['name' => 'Senior Library Assistant (Technical Service)'],
            ['name' => 'Senior Library Assistant (Reader Services)'],
            ['name' => 'Library Assistant (Technical Service)'],
            ['name' => 'Library Assistant (Reader Service)'],
            ['name' => 'Library Attendant (Technical Service)'],
            ['name' => 'Library Attendant (Reader Services)'],
            ['name' => 'ODL Administrator'],
            ['name' => 'ODL Coordinator'],
            ['name' => 'ODL Specialist'],
            ['name' => 'Satellite Center Coordinator'],
            ['name' => 'Campus Coordinator'],
            ['name' => 'Clinic Manager'],
            ['name' => 'Senior Clinical Officer'],
            ['name' => 'Clinical Officer'],
            ['name' => 'Senior Nurse'],
            ['name' => 'Nurse'],
            ['name' => 'Midwife'],
            ['name' => 'Midwife Technician'],
            ['name' => 'Clinic Attendant'],
            ['name' => 'Chief Laboratory Technician'],
            ['name' => 'Laboratory Technician'],
            ['name' => 'Laboratory Attendant'],
            ['name' => 'Laboratory Assistant'],
            ['name' => 'Chief Technician'],
            ['name' => 'Chief Technician in Irrigation & Drainage'],
            ['name' => 'Chief Technician Small Ruminant'],
            ['name' => 'Chief Technician Animal Breeding'],
            ['name' => 'Chief Technician in Plant Breeding'],
            ['name' => 'Chief Technician in Food Analysis'],
            ['name' => 'Chief Technician in Food Service Management'],
            ['name' => 'Chief Technician in Metabolic Analysis'],
            ['name' => 'Chief Technician in Veterinary Anatomy'],
            ['name' => 'Senior Technician in Agronomy'],
            ['name' => 'Senior Technician'],
            ['name' => 'Technician'],
            ['name' => 'Technician in Farm Operations'],
            ['name' => 'Technician in Animal Breeding'],
            ['name' => 'Technician in Physics'],
            ['name' => 'Technician in Biology'],
            ['name' => 'Technician in Maths'],
            ['name' => 'Technician in CHEM/Biochemistry'],
            ['name' => 'Technician in Biochemistry'],
            ['name' => 'Technician in Agronomy'],
            ['name' => 'Technician in Agricultural Extension'],
            ['name' => 'Technician in Food Microbiology'],
            ['name' => 'Technician in Family Science'],
            ['name' => 'Technician in Child & Youth Development'],
            ['name' => 'Technician in Fish Breeding'],
            ['name' => 'Technician in Forest-Wildlife'],
            ['name' => 'Technician in Environmental Science Management'],
            ['name' => 'Technician in Microbiology & Parasitology'],
            ['name' => 'Technician in Public Health & Epidemiology'],
            ['name' => 'Administrative Assistant'],
            ['name' => 'Secretary'],
            ['name' => 'Registry Clerk'],
            ['name' => 'Office Assistant'],
            ['name' => 'Personal Assistant'],
            ['name' => 'Intern'],
            ['name' => 'Switchboard Operator'],
            ['name' => 'Telephone Operator'],
            ['name' => 'Driver'],
            ['name' => 'Porter'],
            ['name' => 'Security Guard'],
            ['name' => 'Cleaner'],
            ['name' => 'Messenger'],
            ['name' => 'Housekeeper'],
            ['name' => 'Electrician'],
            ['name' => 'Carpenter'],
            ['name' => 'Builder'],
            ['name' => 'Brick Layer'],
            ['name' => 'Service Station Sales Assistant'],
            ['name' => 'Filling Station Shift Leader'],
            ['name' => 'Filling Station Manager'],
            ['name' => 'Chief Works Supervisor'],
            ['name' => 'Workshop Assistant'],
            ['name' => 'Workshop Mechanic'],
            ['name' => 'Mechanic'],
            ['name' => 'Fish Farm Manager'],
            ['name' => 'Fruit Crops Production & Sales Foreman'],
            ['name' => 'Agroforestry Foreman'],
            ['name' => 'Vegetable Production Foreman'],
            ['name' => 'Assistant Farm Manager '],
            ['name' => 'Livestock Supervisor'],
            ['name' => 'Crops Supervisor '],
            ['name' => 'Livestock Assistant '],
            ['name' => 'Livestock Attendant'],
            ['name' => 'Field Crops Clerk '],
            ['name' => 'Sales Stores Clerk '],
            ['name' => 'Sales Assistant'],
            ['name' => 'Field Supervisor'],
            ['name' => 'Field Assistant'],
            ['name' => 'Field Crop Supervisor']
        ];

        foreach ($positions as $position) {
            $obj = new Position();
            $obj->name = $position['name'];
            $obj->save();
        }

    }

}
